### ISSUE TITLE
Downloading reports.

### ISSUE THREAD

**Issue by solipsist01** [martingegenleitner/sta#1]
Hello.

Thank you for this sample code.
I was able to query most stuff i needed.

Except, downloading reports. I just can't get it to work.
Did you manage to successfully download reports by any chance ?

I came up with the following code:

```
$safenet_us_portal_login = "username@anon.com"
$safenet_us_portal_password = "redacted"
$companyname = "Sample Company (UBB)"

$client = New-WebServiceProxy -Uri https://cloud.safenet-inc.com/bsidca/BSIDCA.asmx?WSDL

$client.get
$client.CookieContainer = New-Object System.Net.CookieContainer
$client.Connect($safenet_us_portal_login, $safenet_us_portal_password, $null, [ref]$null)

$reports = $client.GetFinishedReports('ServiceProvider', '1', '99999', $companyname)
$report = $reports | select -last 1
$reportdate = get-date $report.scheduledTime -format "yyyy-MM-ddTHH:mm:ss.fffffffzzzz"
$HTML = $client.GetReportOutput('ServiceProvider', $report.reportname, $reportdate, $companyname, 'HTML')
$CSV = $client.GetReportOutput('ServiceProvider', $report.reportname, $reportdate, $companyname, 'CSV')

$HTML
$CSV
```

HTML output is garbled (just an array of numbers, which i also cannot convert to an UTF-8 file)
CSV is completely empty

**Comment by martingegenleitner** [comment]
Hoi, I really thought that I would have some time to get into this, but unfortunately this is not the case. May I ask you to file a ticket at supportportal.thalesgroup.com? The support colleagues will handle your request much faster than I am able to. I am sorry for the late reply. Best regards

**Comment by martingegenleitner** [comment]
Hello again,

I just found out what is causing you problems: The output one receives requesting GetReportOutput() is base64 encoded. powershell converts that into a byte array which can be transformed into a string by using `[System.Text.Encoding]::ASCII.GetString($HTML)`.

So by just adding this line to your script shall print out the report on the console.
